<?php
/**
 * Controller is the customized base controller class.
 * All controller classes for this application should extend from this base class.
 */
class UController extends CController
{
	/**
	 * @var string the default layout for the controller view.
	 */
	public $layout='/layouts/main';
    
    public $pageTitle = null;

    public $pageDescription = null;

    public $buttons = null;

    protected function beforeRender($view)
    {
        /** @var CClientScript $cs */
        $cs = Yii::app()->clientScript;
        $cs->registerPackage('admin');
        return parent::beforeRender($view); // TODO: Change the autogenerated stub
    }


    /**
     * @var array the breadcrumbs of the current page. The value of this property will
     * be assigned to {@link CBreadcrumbs::links}. Please refer to {@link CBreadcrumbs::links}
     * for more details on how to specify this property.
     */
    public $breadcrumbs=array();

    public function disableLoggers(array $logNamesArray = null)
    {
        if(count($logNamesArray))
        {
            for ($i=0; $i < count($logNamesArray); $i++) { 
                foreach (Yii::app()->log->routes as $route)
                {
                    if ($route instanceof $logNamesArray[$i])
                    {
                        $route->enabled = false;
                    }
                }
            }
        } else {
            foreach (Yii::app()->log->routes as $route)
            {
                if ($route instanceof CWebLogRoute || $route instanceof CProfileLogRoute)
                {
                    $route->enabled = false;
                }
            }
        }
        
    }

    protected function sendJson($data)
    {
        $this->disableLoggers();
        if (!headers_sent()) header('Content-Type: application/json; charset="'.Yii::app()->charset.'"');
        echo CJSON::encode($data);
        Yii::app()->end();
    }

    /**
     * @return Users
     */
    public function getUser()
    {
        return Yii::app()->user->getModel();
    }

    public function setFlash($type, $text)
    {
        Yii::app()->user->setFlash($type, '<strong>'.$text.'</strong>');
    }
}